# Generated by Django 3.0.7 on 2020-06-20 15:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college', models.CharField(default='', max_length=100, verbose_name='College Name')),
                ('year', models.CharField(default='', max_length=30, verbose_name='Year')),
                ('branch', models.CharField(default='', max_length=30, verbose_name='Branch')),
                ('id_proof', models.CharField(default='', max_length=30, verbose_name='ID Proof')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
